#!/bin/bash
# TSXS Polar Alignment v2.0 — Linux installer
# Auto-generated by make_linux_install.py.
#
# Usage:  bash install.sh
#
# Installs entirely under ~/.local/ — no sudo required.
# Uninstall: bash install.sh --uninstall

set -e

APP_NAME="TSXS Polar Alignment"
SCRIPT="PAUI.py"
ICON="tsxpolar.png"

INSTALL_DIR="$HOME/.local/share/tsxpolar"
BIN_DIR="$HOME/.local/bin"
ICON_DIR="$HOME/.local/share/icons"
DESKTOP_DIR="$HOME/.local/share/applications"
LAUNCHER="$BIN_DIR/tsxpolar"
DESKTOP_FILE="$DESKTOP_DIR/tsxpolar.desktop"

# ── Uninstall ─────────────────────────────────────────────────────────────────
if [ "$1" = "--uninstall" ]; then
    echo "Removing $APP_NAME..."
    rm -rf  "$INSTALL_DIR"
    rm -f   "$LAUNCHER"
    rm -f   "$ICON_DIR/$ICON"
    rm -f   "$DESKTOP_FILE"
    command -v update-desktop-database &>/dev/null && update-desktop-database "$DESKTOP_DIR" 2>/dev/null || true
    # Always clear the first-run flag so a future install shows first-run setup
    # again, regardless of whether settings/cache below are kept.
    rm -f "$HOME/.tsxpolar_cache/.tsxpolar_ready"
    echo ""
    read -p "Remove settings and cached data? [y/N] " _ud
    if [[ "$_ud" =~ ^[Yy]$ ]]; then
    rm -f "$HOME/.tsxpolar.json"
    rm -rf "$HOME/.tsxpolar_cache"
        echo "Settings removed."
    fi
    echo ""
    echo "WARNING: Do NOT remove uv if you use it for other Python projects."
    read -p "Remove uv? [y/N] " _ruv
    if [[ "$_ruv" =~ ^[Yy]$ ]]; then
        rm -f "$HOME/.local/bin/uv" "$HOME/.local/bin/uvx"
        rm -rf "$HOME/.local/share/uv"
        echo "uv removed."
    fi
    echo ""
    echo "$APP_NAME uninstalled."
    exit 0
fi

# ── Locate the directory containing this script ───────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# ── Create target directories ─────────────────────────────────────────────────
mkdir -p "$INSTALL_DIR" "$BIN_DIR" "$ICON_DIR" "$DESKTOP_DIR"

# ── Copy app script ───────────────────────────────────────────────────────────
echo "  App:      $INSTALL_DIR/$SCRIPT"
cp -f "$SCRIPT_DIR/$SCRIPT" "$INSTALL_DIR/"
chmod +x "$INSTALL_DIR/$SCRIPT"

# ── Copy icon ─────────────────────────────────────────────────────────────────
echo "  Icon:     $ICON_DIR/$ICON"
cp -f "$SCRIPT_DIR/$ICON" "$ICON_DIR/$ICON"

# ── Copy first_run.sh ─────────────────────────────────────────────────────────
echo "  First run:$INSTALL_DIR/first_run.sh"
cp -f "$SCRIPT_DIR/first_run.sh" "$INSTALL_DIR/first_run.sh"
chmod +x "$INSTALL_DIR/first_run.sh"

# Note: the ready flag is deliberately NOT cleared here. On a genuine first
# install it won't exist yet, so the launcher shows the terminal setup window
# as normal. On an update over an existing install it already exists (uv's
# downloads are minimal on an update), so the update launches straight into
# the app with no terminal popup. --uninstall always clears the flag, so a
# fresh install after a full uninstall still gets the terminal window.

# ── Write launcher script ─────────────────────────────────────────────────────
# Unquoted LAUNCHER_EOF: $HOME/$FLAG/$FIRST_RUN/$INSTALL_DIR expand at install
# time (hardcoded paths in launcher). \$VAR in the heredoc source becomes $VAR
# in the launcher (backslash prevents expansion in heredoc, is consumed).
echo "  Launcher: $LAUNCHER"
FLAG="$HOME/.tsxpolar_cache/.tsxpolar_ready"
FIRST_RUN="$HOME/.local/share/tsxpolar/first_run.sh"
cat > "$LAUNCHER" << LAUNCHER_EOF
#!/bin/bash
export PATH="$HOME/.local/bin:$HOME/.cargo/bin:/usr/local/bin:/usr/bin:/bin:\$PATH"
FLAG="$FLAG"
FIRST_RUN="$FIRST_RUN"
LOG_DIR="$HOME/.tsxpolar_cache"
mkdir -p "\$LOG_DIR"
LOG="\$LOG_DIR/launcher.log"

if [ ! -f "\$FLAG" ]; then
    if command -v gnome-terminal &>/dev/null; then
        gnome-terminal -- bash "\$FIRST_RUN"
    elif command -v lxterminal &>/dev/null; then
        lxterminal -e bash "\$FIRST_RUN"
    elif command -v xterm &>/dev/null; then
        xterm -e bash "\$FIRST_RUN"
    elif command -v konsole &>/dev/null; then
        konsole -e bash "\$FIRST_RUN"
    elif command -v xfce4-terminal &>/dev/null; then
        xfce4-terminal -e "bash '\$FIRST_RUN'"
    else
        bash "\$FIRST_RUN" &
    fi
else
    exec >> "\$LOG" 2>&1
    echo "=== TSXS Polar Alignment started \$(date) ==="
    cd "$INSTALL_DIR"
    exec uv run "PAUI.py"
fi
LAUNCHER_EOF
chmod +x "$LAUNCHER"

# ── Write .desktop entry ──────────────────────────────────────────────────────
echo "  Desktop:  $DESKTOP_FILE"
cat > "$DESKTOP_FILE" << EOF
[Desktop Entry]
Version=1.0
Type=Application
Terminal=false
Exec=$LAUNCHER
Name=$APP_NAME
Icon=$ICON_DIR/$ICON
Categories=Education;Science;
Comment=TSXS Polar Alignment Tool v2.0
EOF

# ── Refresh desktop database ──────────────────────────────────────────────────
command -v update-desktop-database &>/dev/null && update-desktop-database "$DESKTOP_DIR" 2>/dev/null || true

echo ""
echo "$APP_NAME v2.0 installed."
echo "Launch from your application menu, or run:  tsxpolar"
echo "(Ensure ~/.local/bin is in your PATH if the command is not found.)"
