#!/bin/bash
# TSXS Polar Alignment v2.0 — Linux installer
# Auto-generated by make_linux_install.py.
#
# Usage:  bash install.sh                 (also puts an icon on the Desktop)
#         bash install.sh --no-desktop    (menu entry only)
#
# Installs entirely under ~/.local/ — no sudo required.
# Uninstall: bash install.sh --uninstall  (a copy is kept in the install dir)

set -e

APP_NAME="TSXS Polar Alignment"
SCRIPT="PAUI.py"
ICON="tsxpolar.png"

INSTALL_DIR="$HOME/.local/share/tsxpolar"
BIN_DIR="$HOME/.local/bin"
ICON_DIR="$HOME/.local/share/icons"
DESKTOP_DIR="$HOME/.local/share/applications"
LAUNCHER="$BIN_DIR/tsxpolar"
UNINSTALLER="$BIN_DIR/tsxpolar-uninstall"
DESKTOP_FILE="$DESKTOP_DIR/tsxpolar.desktop"

# The Desktop folder is localised -- Bureau, Schreibtisch, Skrivebord -- so ask
# rather than assume, falling back to the English name if xdg-user-dir is not
# installed.
DESKTOP_HOME="$(xdg-user-dir DESKTOP 2>/dev/null || true)"
[ -z "$DESKTOP_HOME" ] && DESKTOP_HOME="$HOME/Desktop"
DESKTOP_SHORTCUT="$DESKTOP_HOME/tsxpolar.desktop"

WANT_DESKTOP=1
[ "$1" = "--no-desktop" ] && WANT_DESKTOP=0

# ── Uninstall ─────────────────────────────────────────────────────────────────
if [ "$1" = "--uninstall" ]; then
    echo "Removing $APP_NAME..."
    rm -rf  "$INSTALL_DIR"
    rm -f   "$LAUNCHER"
    rm -f   "$UNINSTALLER"
    rm -f   "$ICON_DIR/$ICON"
    rm -f   "$DESKTOP_FILE"
    rm -f   "$DESKTOP_SHORTCUT"
    command -v update-desktop-database &>/dev/null && update-desktop-database "$DESKTOP_DIR" 2>/dev/null || true
    # Always clear the first-run flag so a future install shows first-run setup
    # again, regardless of whether settings/cache below are kept.
    rm -f "$HOME/.tsxpolar_cache/.tsxpolar_ready"
    echo ""
    read -p "Remove settings and cached data? [y/N] " _ud
    if [[ "$_ud" =~ ^[Yy]$ ]]; then
    rm -f "$HOME/.tsxpolar.json"
    rm -rf "$HOME/.tsxpolar_cache"
        echo "Settings removed."
    fi
    echo ""
    echo "WARNING: Do NOT remove uv if you use it for other Python projects."
    read -p "Remove uv? [y/N] " _ruv
    if [[ "$_ruv" =~ ^[Yy]$ ]]; then
        rm -f "$HOME/.local/bin/uv" "$HOME/.local/bin/uvx"
        rm -rf "$HOME/.local/share/uv"
        echo "uv removed."
    fi
    echo ""
    echo "$APP_NAME uninstalled."
    exit 0
fi

# ── Locate the directory containing this script ───────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# ── Create target directories ─────────────────────────────────────────────────
mkdir -p "$INSTALL_DIR" "$BIN_DIR" "$ICON_DIR" "$DESKTOP_DIR"

# ── Copy app script ───────────────────────────────────────────────────────────
echo "  App:      $INSTALL_DIR/$SCRIPT"
cp -f "$SCRIPT_DIR/$SCRIPT" "$INSTALL_DIR/"
chmod +x "$INSTALL_DIR/$SCRIPT"

# ── Copy icon ─────────────────────────────────────────────────────────────────
echo "  Icon:     $ICON_DIR/$ICON"
cp -f "$SCRIPT_DIR/$ICON" "$ICON_DIR/$ICON"

# ── Copy first_run.sh ─────────────────────────────────────────────────────────
echo "  First run:$INSTALL_DIR/first_run.sh"
cp -f "$SCRIPT_DIR/first_run.sh" "$INSTALL_DIR/first_run.sh"
chmod +x "$INSTALL_DIR/first_run.sh"

# ── Keep a copy of this installer ─────────────────────────────────────────────
# Uninstalling is "install.sh --uninstall", so without this the only copy is in
# whatever folder the download was unzipped into -- delete that and the app can
# no longer be removed.
cp -f "$SCRIPT_DIR/$(basename "$0")" "$INSTALL_DIR/install.sh"
chmod +x "$INSTALL_DIR/install.sh"

# ── Uninstall command ─────────────────────────────────────────────────────────
# ~/.local/bin is shared by all the TSXS apps, so this is named after the app
# rather than being a bare "uninstall" that each install would overwrite in
# turn -- the last one installed would then uninstall the wrong program.
echo "  Uninstall:$UNINSTALLER"
cat > "$UNINSTALLER" << UNINSTALL_EOF
#!/bin/bash
exec bash "$INSTALL_DIR/install.sh" --uninstall
UNINSTALL_EOF
chmod +x "$UNINSTALLER"

# Note: the ready flag is deliberately NOT cleared here. On a genuine first
# install it won't exist yet, so the launcher shows the terminal setup window
# as normal. On an update over an existing install it already exists (uv's
# downloads are minimal on an update), so the update launches straight into
# the app with no terminal popup. --uninstall always clears the flag, so a
# fresh install after a full uninstall still gets the terminal window.

# ── Write launcher script ─────────────────────────────────────────────────────
# Unquoted LAUNCHER_EOF: $HOME/$FLAG/$FIRST_RUN/$INSTALL_DIR expand at install
# time (hardcoded paths in launcher). \$VAR in the heredoc source becomes $VAR
# in the launcher (backslash prevents expansion in heredoc, is consumed).
echo "  Launcher: $LAUNCHER"
FLAG="$HOME/.tsxpolar_cache/.tsxpolar_ready"
FIRST_RUN="$HOME/.local/share/tsxpolar/first_run.sh"
cat > "$LAUNCHER" << LAUNCHER_EOF
#!/bin/bash
export PATH="$HOME/.local/bin:$HOME/.cargo/bin:/usr/local/bin:/usr/bin:/bin:\$PATH"
FLAG="$FLAG"
FIRST_RUN="$FIRST_RUN"
LOG_DIR="$HOME/.tsxpolar_cache"
mkdir -p "\$LOG_DIR"
LOG="\$LOG_DIR/launcher.log"

if [ ! -f "\$FLAG" ]; then
    if command -v gnome-terminal &>/dev/null; then
        gnome-terminal -- bash "\$FIRST_RUN"
    elif command -v lxterminal &>/dev/null; then
        lxterminal -e bash "\$FIRST_RUN"
    elif command -v xterm &>/dev/null; then
        xterm -e bash "\$FIRST_RUN"
    elif command -v konsole &>/dev/null; then
        konsole -e bash "\$FIRST_RUN"
    elif command -v xfce4-terminal &>/dev/null; then
        xfce4-terminal -e "bash '\$FIRST_RUN'"
    else
        bash "\$FIRST_RUN" &
    fi
else
    exec >> "\$LOG" 2>&1
    echo "=== TSXS Polar Alignment started \$(date) ==="
    cd "$INSTALL_DIR"
    exec uv run "PAUI.py"
fi
LAUNCHER_EOF
chmod +x "$LAUNCHER"

# ── Write .desktop entry ──────────────────────────────────────────────────────
echo "  Desktop:  $DESKTOP_FILE"
cat > "$DESKTOP_FILE" << EOF
[Desktop Entry]
Version=1.0
Type=Application
Terminal=false
Exec=$LAUNCHER
Name=$APP_NAME
Icon=$ICON_DIR/$ICON
Categories=Education;Science;
Comment=TSXS Polar Alignment Tool v2.0
EOF

# ── Refresh desktop database ──────────────────────────────────────────────────
command -v update-desktop-database &>/dev/null && update-desktop-database "$DESKTOP_DIR" 2>/dev/null || true

# ── Copy the same entry to the Desktop ────────────────────────────────────────
# The menu entry above is the standard mechanism, but it leaves nothing to
# double-click, which is how most people expect to start a program.  Two
# details decide whether this works: the file has to be executable, or most
# desktops show it as a text file; and GNOME additionally wants it marked
# trusted, or it appears as "Untrusted application launcher".  The gio call is
# harmless everywhere else.
if [ "$WANT_DESKTOP" = "1" ] && [ -d "$DESKTOP_HOME" ]; then
    cp -f "$DESKTOP_FILE" "$DESKTOP_SHORTCUT"
    chmod +x "$DESKTOP_SHORTCUT"
    command -v gio &>/dev/null &&         gio set "$DESKTOP_SHORTCUT" metadata::trusted true 2>/dev/null || true
    echo "  Shortcut: $DESKTOP_SHORTCUT"
elif [ "$WANT_DESKTOP" = "1" ]; then
    echo "  Shortcut: no Desktop folder found — skipped"
fi

# ── Say where everything went ─────────────────────────────────────────────────
echo ""
echo "$APP_NAME v2.0 installed."
echo ""
echo "  Start it       double-click the Desktop icon, choose $APP_NAME from"
echo "                 the application menu, or run:  tsxpolar"
echo "  Program files  $INSTALL_DIR"
echo "  Settings       $HOME/.tsxpolar.json"
echo "  Log            $HOME/.tsxpolar_cache/launcher.log"
echo "  Uninstall      tsxpolar-uninstall"
echo ""
echo "(If the tsxpolar command is not found, log out and back in so that"
echo " ~/.local/bin is added to your PATH.)"
