# TSXS Polar Alignment v2.0 - Windows installer
# Auto-generated by make_windows.py.
#
# Usage (run install.bat, or from PowerShell):
#   .\install.ps1
#
# If PowerShell blocks the script, first run:
#   Set-ExecutionPolicy -Scope CurrentUser -ExecutionPolicy RemoteSigned
#
# Uninstall:
#   .\install.ps1 -Uninstall

param([switch]$Uninstall)

$AppName      = "TSXS Polar Alignment"
$Version      = "2.0"
$Script       = "PAUI.py"
$Icon         = "tsxpolar.ico"
$InstallDir   = "$env:LOCALAPPDATA\tsxpolar"
$StartMenuDir = "$env:APPDATA\Microsoft\Windows\Start Menu\Programs"
$Desktop      = [Environment]::GetFolderPath("Desktop")
$ShortcutName = "$AppName.lnk"

# ── Uninstall ─────────────────────────────────────────────────────────────────
if ($Uninstall) {
    Write-Host "Removing $AppName..."
    Remove-Item -Recurse -Force $InstallDir -ErrorAction SilentlyContinue
    Remove-Item -Force "$Desktop\$ShortcutName"      -ErrorAction SilentlyContinue
    Remove-Item -Force "$StartMenuDir\$ShortcutName" -ErrorAction SilentlyContinue
    # Always clear the first-run flag so a future install shows first-run setup again,
    # regardless of whether the user keeps their other settings/cache below.
    Remove-Item -Force "$env:USERPROFILE\.tsxpolar_cache\.tsxpolar_ready" -ErrorAction SilentlyContinue

    Add-Type -AssemblyName System.Windows.Forms
    $r = [System.Windows.Forms.MessageBox]::Show(
        "Do you also want to remove your settings and cached data?`n`nThis cannot be undone.",
        "Uninstall $AppName",
        [System.Windows.Forms.MessageBoxButtons]::YesNo,
        [System.Windows.Forms.MessageBoxIcon]::Question
    )
    if ($r -eq [System.Windows.Forms.DialogResult]::Yes) {
        Remove-Item -Force "$env:USERPROFILE\.tsxpolar.json" -ErrorAction SilentlyContinue
        Remove-Item -Recurse -Force "$env:USERPROFILE\.tsxpolar_cache" -ErrorAction SilentlyContinue
        Write-Host "Settings and cached data removed."
    }

    $uvMsg = "Do you also want to remove uv (the Python package manager)?`n`n" +
             "WARNING: Do NOT remove uv if you use it for other Python projects.`n`n" +
             "Click Yes to remove uv, No to keep it."
    $ruv = [System.Windows.Forms.MessageBox]::Show(
        $uvMsg,
        "Uninstall $AppName",
        [System.Windows.Forms.MessageBoxButtons]::YesNo,
        [System.Windows.Forms.MessageBoxIcon]::Warning
    )
    if ($ruv -eq [System.Windows.Forms.DialogResult]::Yes) {
        Remove-Item -Force "$env:USERPROFILE\.local\bin\uv.exe"  -ErrorAction SilentlyContinue
        Remove-Item -Force "$env:USERPROFILE\.local\bin\uvx.exe" -ErrorAction SilentlyContinue
        Remove-Item -Recurse -Force "$env:LOCALAPPDATA\astral"     -ErrorAction SilentlyContinue
        Remove-Item -Recurse -Force "$env:LOCALAPPDATA\uv"         -ErrorAction SilentlyContinue
        Write-Host "uv removed."
    }

    Write-Host "$AppName uninstalled."
    exit 0
}

# ── Locate the folder this script is in ───────────────────────────────────────
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path

# ── Create install directory ──────────────────────────────────────────────────
$null = New-Item -ItemType Directory -Force -Path $InstallDir
Write-Host "  Install dir: $InstallDir"

# ── Copy files ────────────────────────────────────────────────────────────────
foreach ($file in @($Script, $Icon, "launch.vbs", "launch.ps1", "install.ps1", "uninstall.bat")) {
    $src = "$ScriptDir\$file"
    if (Test-Path $src) {
        Copy-Item -Force $src "$InstallDir\$file"
        Write-Host "  Copied:      $file"
    }
}

# Note: the ready flag is deliberately NOT cleared here. On a genuine first
# install it won't exist yet, so the launcher shows the PowerShell setup
# window as normal. On an update over an existing install it already exists
# (uv's downloads are minimal on an update), so the update launches straight
# into the app with no setup window. Uninstall always clears the flag, so a
# fresh install after a full uninstall still gets the setup window.

# ── Create shortcuts ──────────────────────────────────────────────────────────
$WshShell = New-Object -ComObject WScript.Shell
foreach ($dest in @("$Desktop\$ShortcutName", "$StartMenuDir\$ShortcutName")) {
    $sc = $WshShell.CreateShortcut($dest)
    $sc.TargetPath       = "wscript.exe"
    $sc.Arguments        = "`"$InstallDir\launch.vbs`""
    $sc.WorkingDirectory = $InstallDir
    $sc.Description      = "TSXS Polar Alignment Tool v2.0"
    if (Test-Path "$InstallDir\$Icon") {
        $sc.IconLocation = "$InstallDir\$Icon,0"
    }
    $sc.Save()
    Write-Host "  Shortcut:    $dest"
}

Write-Host ""
Write-Host "$AppName v$Version installed."
Write-Host "Launch from your Desktop or Start Menu."
