# TSXS Polar Alignment v2.0 - PowerShell launcher
# Auto-generated by make_windows.py.

# Add common uv install locations to PATH
$uvBin = "$env:USERPROFILE\.local\bin"
$uvAlt = "$env:LOCALAPPDATA\astral\uv\bin"
if ($env:PATH -notlike "*$uvBin*") { $env:PATH = "$uvBin;$uvAlt;$env:PATH" }

$LogDir   = "$env:USERPROFILE\.tsxpolar_cache"
$null     = New-Item -ItemType Directory -Force -Path $LogDir
$LogFile  = "$LogDir\launcher.log"
$ReadyFlag = "$LogDir\.tsxpolar_ready"
$FirstRun  = -not (Test-Path $ReadyFlag)

"=== TSXS Polar Alignment started $(Get-Date) ===" | Out-File -FilePath $LogFile -Encoding UTF8
"Install dir: $PSScriptRoot" | Add-Content -Path $LogFile -Encoding UTF8

if ($FirstRun) {
    Write-Host ""
    Write-Host "============================================"
    Write-Host "  TSXS Polar Alignment v2.0 - First Run Setup"
    Write-Host "============================================"
    Write-Host ""
    Write-Host "This window shows progress during first-time setup."
    Write-Host "It will not appear on future launches."
    Write-Host ""
}

if (-not (Get-Command uv -ErrorAction SilentlyContinue)) {
    if ($FirstRun) {
        Write-Host "Step 1: Installing uv (Python package manager)..."
        Write-Host "        This is a one-time download (~30 seconds)."
        Write-Host ""
    } else {
        Add-Type -AssemblyName System.Windows.Forms
        $msg = "uv (Python package manager) is not installed.`n`nClick OK to install it now (one-time, ~30 seconds)."
        $r = [System.Windows.Forms.MessageBox]::Show($msg, "TSXS Polar Alignment", "OKCancel", "Information")
        if ($r -ne "OK") { exit 0 }
    }
    try {
        Invoke-RestMethod https://astral.sh/uv/install.ps1 | Invoke-Expression
        $env:PATH = "$uvBin;$env:PATH"
        if ($FirstRun) { Write-Host "        uv installed successfully."; Write-Host "" }
    } catch {
        $emsg = "uv installation failed. Please install from https://docs.astral.sh/uv/"
        if ($FirstRun) { Write-Host "ERROR: $emsg" } else {
            Add-Type -AssemblyName System.Windows.Forms
            [System.Windows.Forms.MessageBox]::Show($emsg, "TSXS Polar Alignment", "OK", "Error") | Out-Null
        }
        "uv install error: $_" | Add-Content -FilePath $LogFile -Encoding UTF8
        exit 1
    }
}

if (-not (Get-Command uv -ErrorAction SilentlyContinue)) {
    $emsg = "uv not found after installation. Please install from https://docs.astral.sh/uv/"
    if ($FirstRun) { Write-Host "ERROR: $emsg" } else {
        Add-Type -AssemblyName System.Windows.Forms
        [System.Windows.Forms.MessageBox]::Show($emsg, "TSXS Polar Alignment", "OK", "Error") | Out-Null
    }
    exit 1
}

if ($FirstRun) {
    Write-Host "Step 2: Downloading app packages..."
    Write-Host "        This may take a minute on a slow connection."
    Write-Host ""
}

Set-Location $PSScriptRoot
"Starting: uv run PAUI.py" | Add-Content -Path $LogFile -Encoding UTF8

if ($FirstRun) {
    Write-Host "Step 3: Starting TSXS Polar Alignment..."
    Write-Host "        (This window will close when you close the app.)"
    Write-Host ""
}

& uv run "PAUI.py"

if ($FirstRun) {
    New-Item -ItemType File -Force -Path $ReadyFlag | Out-Null
    "First run complete - future launches will be silent." | Add-Content -Path $LogFile -Encoding UTF8
}
